/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Image: typeof import('./src/components/Image.vue')['default']
    InfiniteScroll: typeof import('./src/components/InfiniteScroll.vue')['default']
    InfiniteScrollList: typeof import('./src/components/InfiniteScrollList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Text: typeof import('./src/components/Text.vue')['default']
    View: typeof import('./src/components/View.vue')['default']
  }
}

// For TSX support
declare global {
  const Image: typeof import('./src/components/Image.vue')['default']
  const InfiniteScroll: typeof import('./src/components/InfiniteScroll.vue')['default']
  const InfiniteScrollList: typeof import('./src/components/InfiniteScrollList.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Text: typeof import('./src/components/Text.vue')['default']
  const View: typeof import('./src/components/View.vue')['default']
}